server:
  port: 9192

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3306/sbr_db2
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
      database-platform: org.hibernate.dialect.MySQL57Dialect